apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: randomizer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/david-bour/portfolio.git
    targetRevision: main
    path: ./ops/deployment/deployments/apps/environments/dev
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: randomizer-dev