name: Build and Deploy API

on:
  workflow_dispatch:
  push:
  #   branches:
  #     - main
  #   paths:
  #     - "api/**"
  # pull_request:
  #   branches:
  #     - main
  #   paths:
  #     - "api/**"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/650273226296/locations/global/workloadIdentityPools/gh-actions-pool/providers/gh-actions'
          service_account: 'github-actions@cloudresume-380001.iam.gserviceaccount.com'
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - run: docker build -t gcr.io/cloudresume-380001/visitor-api:${{ github.sha }} .
        working-directory: api

      - run: docker push --all-tags

      # - name: Build and Push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: "./api"
      #     push: true
      #     tags: gcr.io/cloudresume-380001/visitor-api:${{ github.sha }}


      # - id: 'deploy'
      #   uses: 'google-github-actions/deploy-cloudrun@v1'
      #   with:
      #     service: 'visitor-api'
      #     image: 