name: Build Randomizer

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "randomizer/**"
  pull_request:
    branches:
      - main
    paths:
      - "randomizer/**"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/774194386647/locations/global/workloadIdentityPools/gh-actions-pool/providers/gh-actions'
          service_account: 'github-actions@cloudops-388321.iam.gserviceaccount.com'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: "./randomizer"
          push: true
          tags: gcr.io/cloudops-388321/randomizer:${{ github.sha }}
