name: Destroy Terraform

on:
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/774194386647/locations/global/workloadIdentityPools/gh-actions-pool/providers/gh-actions'
          service_account: 'tf-provider@cloudops-388321.iam.gserviceaccount.com'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.2
          cli_config_credentials_token: ${{ steps.auth.outputs.access_token }}

      - name: Terraform Clean
        run: terraform destroy -auto-approve
        working-directory: ops/deployment/infrastructure/terraform